2022-09-04 20:33:57,006 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
2022-09-04 20:34:00,491 ERROR: Exception on /admin [GET] [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/routes.py", line 268, in admin
    return render_template('admin.html', title='Admin', form=form, lines=dates.items, next_url=next_url, prev_url=prev_url)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/templates/admin.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/templates/base.html", line 45, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2022-09-04 20:35:01,099 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
2022-09-04 20:46:53,254 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
2022-09-05 19:59:30,069 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
2022-09-06 17:48:15,174 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
2022-09-06 17:55:51,336 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
2022-09-06 17:56:15,105 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
2022-09-06 17:56:17,801 ERROR: Exception on /user/daniel [GET] [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/routes.py", line 15, in before_request
    if current_user.is_authenticated:
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/werkzeug/local.py", line 436, in __get__
    obj = instance._get_current_object()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/werkzeug/local.py", line 565, in _get_current_object
    return self.__local()  # type: ignore
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask_login/login_manager.py", line 318, in _load_user
    user = self._user_callback(user_id)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/models.py", line 59, in load_user
    return User.query.get(int(id))
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 550, in __get__
    mapper = orm.class_mapper(type)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/sqlalchemy/orm/base.py", line 442, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/sqlalchemy/orm/base.py", line 421, in _inspect_mapped_class
    mapper._check_configure()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 1900, in _check_configure
    _configure_registries({self.registry}, cascade=True)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 3418, in _configure_registries
    _do_configure_registries(registries, cascade)
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 3457, in _do_configure_registries
    mapper._post_configure_properties()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/sqlalchemy/orm/mapper.py", line 1917, in _post_configure_properties
    prop.init()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 2155, in do_init
    self._generate_backref()
  File "/Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/chalenv/lib/python3.10/site-packages/sqlalchemy/orm/relationships.py", line 2435, in _generate_backref
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Error creating backref 'id' on relationship 'User.bookings': property of that name exists on mapper 'mapped class Period->period'
2022-09-06 17:59:18,193 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
2022-09-06 18:40:11,591 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
2022-09-06 18:41:39,969 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
2022-09-06 22:03:57,332 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
2022-09-06 22:07:53,465 INFO: Microblog startup [in /Users/danielbianco/Documents/Flask/Tests/RentChalet WIP/app/__init__.py:47]
